// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uploaded_file.proto

package com.nexterdigital.nextershop.pb.uploadedfile;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uploadedfile.v1.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source = 1;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 1;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();
}
