// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uploaded_file.proto

package com.nexterdigital.nextershop.pb.uploadedfile;

/**
 * Protobuf type {@code uploadedfile.v1.Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:uploadedfile.v1.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    uploadedFiles_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Response();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              uploadedFiles_ = new java.util.ArrayList<com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile>();
              mutable_bitField0_ |= 0x00000001;
            }
            uploadedFiles_.add(
                input.readMessage(com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        uploadedFiles_ = java.util.Collections.unmodifiableList(uploadedFiles_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileProto.internal_static_uploadedfile_v1_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileProto.internal_static_uploadedfile_v1_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nexterdigital.nextershop.pb.uploadedfile.Response.class, com.nexterdigital.nextershop.pb.uploadedfile.Response.Builder.class);
  }

  public static final int UPLOADED_FILES_FIELD_NUMBER = 1;
  private java.util.List<com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile> uploadedFiles_;
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile> getUploadedFilesList() {
    return uploadedFiles_;
  }
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder> 
      getUploadedFilesOrBuilderList() {
    return uploadedFiles_;
  }
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  @java.lang.Override
  public int getUploadedFilesCount() {
    return uploadedFiles_.size();
  }
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  @java.lang.Override
  public com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile getUploadedFiles(int index) {
    return uploadedFiles_.get(index);
  }
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  @java.lang.Override
  public com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder getUploadedFilesOrBuilder(
      int index) {
    return uploadedFiles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < uploadedFiles_.size(); i++) {
      output.writeMessage(1, uploadedFiles_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < uploadedFiles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, uploadedFiles_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nexterdigital.nextershop.pb.uploadedfile.Response)) {
      return super.equals(obj);
    }
    com.nexterdigital.nextershop.pb.uploadedfile.Response other = (com.nexterdigital.nextershop.pb.uploadedfile.Response) obj;

    if (!getUploadedFilesList()
        .equals(other.getUploadedFilesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUploadedFilesCount() > 0) {
      hash = (37 * hash) + UPLOADED_FILES_FIELD_NUMBER;
      hash = (53 * hash) + getUploadedFilesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nexterdigital.nextershop.pb.uploadedfile.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nexterdigital.nextershop.pb.uploadedfile.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code uploadedfile.v1.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:uploadedfile.v1.Response)
      com.nexterdigital.nextershop.pb.uploadedfile.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileProto.internal_static_uploadedfile_v1_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileProto.internal_static_uploadedfile_v1_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nexterdigital.nextershop.pb.uploadedfile.Response.class, com.nexterdigital.nextershop.pb.uploadedfile.Response.Builder.class);
    }

    // Construct using com.nexterdigital.nextershop.pb.uploadedfile.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUploadedFilesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (uploadedFilesBuilder_ == null) {
        uploadedFiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        uploadedFilesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileProto.internal_static_uploadedfile_v1_Response_descriptor;
    }

    @java.lang.Override
    public com.nexterdigital.nextershop.pb.uploadedfile.Response getDefaultInstanceForType() {
      return com.nexterdigital.nextershop.pb.uploadedfile.Response.getDefaultInstance();
    }

    @java.lang.Override
    public com.nexterdigital.nextershop.pb.uploadedfile.Response build() {
      com.nexterdigital.nextershop.pb.uploadedfile.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nexterdigital.nextershop.pb.uploadedfile.Response buildPartial() {
      com.nexterdigital.nextershop.pb.uploadedfile.Response result = new com.nexterdigital.nextershop.pb.uploadedfile.Response(this);
      int from_bitField0_ = bitField0_;
      if (uploadedFilesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          uploadedFiles_ = java.util.Collections.unmodifiableList(uploadedFiles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uploadedFiles_ = uploadedFiles_;
      } else {
        result.uploadedFiles_ = uploadedFilesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nexterdigital.nextershop.pb.uploadedfile.Response) {
        return mergeFrom((com.nexterdigital.nextershop.pb.uploadedfile.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nexterdigital.nextershop.pb.uploadedfile.Response other) {
      if (other == com.nexterdigital.nextershop.pb.uploadedfile.Response.getDefaultInstance()) return this;
      if (uploadedFilesBuilder_ == null) {
        if (!other.uploadedFiles_.isEmpty()) {
          if (uploadedFiles_.isEmpty()) {
            uploadedFiles_ = other.uploadedFiles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUploadedFilesIsMutable();
            uploadedFiles_.addAll(other.uploadedFiles_);
          }
          onChanged();
        }
      } else {
        if (!other.uploadedFiles_.isEmpty()) {
          if (uploadedFilesBuilder_.isEmpty()) {
            uploadedFilesBuilder_.dispose();
            uploadedFilesBuilder_ = null;
            uploadedFiles_ = other.uploadedFiles_;
            bitField0_ = (bitField0_ & ~0x00000001);
            uploadedFilesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUploadedFilesFieldBuilder() : null;
          } else {
            uploadedFilesBuilder_.addAllMessages(other.uploadedFiles_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nexterdigital.nextershop.pb.uploadedfile.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nexterdigital.nextershop.pb.uploadedfile.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile> uploadedFiles_ =
      java.util.Collections.emptyList();
    private void ensureUploadedFilesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        uploadedFiles_ = new java.util.ArrayList<com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile>(uploadedFiles_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder> uploadedFilesBuilder_;

    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public java.util.List<com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile> getUploadedFilesList() {
      if (uploadedFilesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(uploadedFiles_);
      } else {
        return uploadedFilesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public int getUploadedFilesCount() {
      if (uploadedFilesBuilder_ == null) {
        return uploadedFiles_.size();
      } else {
        return uploadedFilesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile getUploadedFiles(int index) {
      if (uploadedFilesBuilder_ == null) {
        return uploadedFiles_.get(index);
      } else {
        return uploadedFilesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder setUploadedFiles(
        int index, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile value) {
      if (uploadedFilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUploadedFilesIsMutable();
        uploadedFiles_.set(index, value);
        onChanged();
      } else {
        uploadedFilesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder setUploadedFiles(
        int index, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder builderForValue) {
      if (uploadedFilesBuilder_ == null) {
        ensureUploadedFilesIsMutable();
        uploadedFiles_.set(index, builderForValue.build());
        onChanged();
      } else {
        uploadedFilesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder addUploadedFiles(com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile value) {
      if (uploadedFilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUploadedFilesIsMutable();
        uploadedFiles_.add(value);
        onChanged();
      } else {
        uploadedFilesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder addUploadedFiles(
        int index, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile value) {
      if (uploadedFilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUploadedFilesIsMutable();
        uploadedFiles_.add(index, value);
        onChanged();
      } else {
        uploadedFilesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder addUploadedFiles(
        com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder builderForValue) {
      if (uploadedFilesBuilder_ == null) {
        ensureUploadedFilesIsMutable();
        uploadedFiles_.add(builderForValue.build());
        onChanged();
      } else {
        uploadedFilesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder addUploadedFiles(
        int index, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder builderForValue) {
      if (uploadedFilesBuilder_ == null) {
        ensureUploadedFilesIsMutable();
        uploadedFiles_.add(index, builderForValue.build());
        onChanged();
      } else {
        uploadedFilesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder addAllUploadedFiles(
        java.lang.Iterable<? extends com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile> values) {
      if (uploadedFilesBuilder_ == null) {
        ensureUploadedFilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uploadedFiles_);
        onChanged();
      } else {
        uploadedFilesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder clearUploadedFiles() {
      if (uploadedFilesBuilder_ == null) {
        uploadedFiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        uploadedFilesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public Builder removeUploadedFiles(int index) {
      if (uploadedFilesBuilder_ == null) {
        ensureUploadedFilesIsMutable();
        uploadedFiles_.remove(index);
        onChanged();
      } else {
        uploadedFilesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder getUploadedFilesBuilder(
        int index) {
      return getUploadedFilesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder getUploadedFilesOrBuilder(
        int index) {
      if (uploadedFilesBuilder_ == null) {
        return uploadedFiles_.get(index);  } else {
        return uploadedFilesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public java.util.List<? extends com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder> 
         getUploadedFilesOrBuilderList() {
      if (uploadedFilesBuilder_ != null) {
        return uploadedFilesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(uploadedFiles_);
      }
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder addUploadedFilesBuilder() {
      return getUploadedFilesFieldBuilder().addBuilder(
          com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.getDefaultInstance());
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder addUploadedFilesBuilder(
        int index) {
      return getUploadedFilesFieldBuilder().addBuilder(
          index, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.getDefaultInstance());
    }
    /**
     * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
     */
    public java.util.List<com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder> 
         getUploadedFilesBuilderList() {
      return getUploadedFilesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder> 
        getUploadedFilesFieldBuilder() {
      if (uploadedFilesBuilder_ == null) {
        uploadedFilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile.Builder, com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder>(
                uploadedFiles_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        uploadedFiles_ = null;
      }
      return uploadedFilesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:uploadedfile.v1.Response)
  }

  // @@protoc_insertion_point(class_scope:uploadedfile.v1.Response)
  private static final com.nexterdigital.nextershop.pb.uploadedfile.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nexterdigital.nextershop.pb.uploadedfile.Response();
  }

  public static com.nexterdigital.nextershop.pb.uploadedfile.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nexterdigital.nextershop.pb.uploadedfile.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

