// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uploaded_file.proto

package com.nexterdigital.nextershop.pb.uploadedfile;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uploadedfile.v1.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  java.util.List<com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile> 
      getUploadedFilesList();
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  com.nexterdigital.nextershop.pb.uploadedfile.UploadedFile getUploadedFiles(int index);
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  int getUploadedFilesCount();
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  java.util.List<? extends com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder> 
      getUploadedFilesOrBuilderList();
  /**
   * <code>repeated .uploadedfile.v1.UploadedFile uploaded_files = 1;</code>
   */
  com.nexterdigital.nextershop.pb.uploadedfile.UploadedFileOrBuilder getUploadedFilesOrBuilder(
      int index);
}
