// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csv.proto

package com.nexterdigital.nextershop.pb.csv;

public final class CsvProto {
  private CsvProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_csv_v1_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_csv_v1_Payload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_csv_v1_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_csv_v1_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcsv.proto\022\006csv.v1\032 google/protobuf/des" +
      "criptor.proto\032\033google/protobuf/empty.pro" +
      "to\032\rproduct.proto\"9\n\007Payload\022&\n\007product\030" +
      "\001 \001(\0132\023.product.v1.ProductH\000B\006\n\004data\"I\n\007" +
      "Request\022\016\n\006ref_id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022 \n" +
      "\007payload\030\003 \003(\0132\017.csv.v1.Payload2C\n\nCsvSe" +
      "rvice\0225\n\010generate\022\017.csv.v1.Request\032\026.goo" +
      "gle.protobuf.Empty\"\000B1\n#com.nexterdigita" +
      "l.nextershop.pb.csvB\010CsvProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.nexterdigital.nextershop.pb.product.ProductProto.getDescriptor(),
        });
    internal_static_csv_v1_Payload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_csv_v1_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_csv_v1_Payload_descriptor,
        new java.lang.String[] { "Product", "Data", });
    internal_static_csv_v1_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_csv_v1_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_csv_v1_Request_descriptor,
        new java.lang.String[] { "RefId", "Name", "Payload", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.nexterdigital.nextershop.pb.product.ProductProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
