// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csv.proto

package com.nexterdigital.nextershop.pb.csv;

/**
 * Protobuf type {@code csv.v1.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:csv.v1.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    name_ = "";
    payload_ = java.util.Collections.emptyList();
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              payload_ = new java.util.ArrayList<com.nexterdigital.nextershop.pb.csv.Payload>();
              mutable_bitField0_ |= 0x00000001;
            }
            payload_.add(
                input.readMessage(com.nexterdigital.nextershop.pb.csv.Payload.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        payload_ = java.util.Collections.unmodifiableList(payload_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nexterdigital.nextershop.pb.csv.CsvProto.internal_static_csv_v1_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nexterdigital.nextershop.pb.csv.CsvProto.internal_static_csv_v1_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nexterdigital.nextershop.pb.csv.Request.class, com.nexterdigital.nextershop.pb.csv.Request.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 2;
  private java.util.List<com.nexterdigital.nextershop.pb.csv.Payload> payload_;
  /**
   * <code>repeated .csv.v1.Payload payload = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.nexterdigital.nextershop.pb.csv.Payload> getPayloadList() {
    return payload_;
  }
  /**
   * <code>repeated .csv.v1.Payload payload = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.nexterdigital.nextershop.pb.csv.PayloadOrBuilder> 
      getPayloadOrBuilderList() {
    return payload_;
  }
  /**
   * <code>repeated .csv.v1.Payload payload = 2;</code>
   */
  @java.lang.Override
  public int getPayloadCount() {
    return payload_.size();
  }
  /**
   * <code>repeated .csv.v1.Payload payload = 2;</code>
   */
  @java.lang.Override
  public com.nexterdigital.nextershop.pb.csv.Payload getPayload(int index) {
    return payload_.get(index);
  }
  /**
   * <code>repeated .csv.v1.Payload payload = 2;</code>
   */
  @java.lang.Override
  public com.nexterdigital.nextershop.pb.csv.PayloadOrBuilder getPayloadOrBuilder(
      int index) {
    return payload_.get(index);
  }

  public static final int ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < payload_.size(); i++) {
      output.writeMessage(2, payload_.get(i));
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < payload_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, payload_.get(i));
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nexterdigital.nextershop.pb.csv.Request)) {
      return super.equals(obj);
    }
    com.nexterdigital.nextershop.pb.csv.Request other = (com.nexterdigital.nextershop.pb.csv.Request) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getPayloadList()
        .equals(other.getPayloadList())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getPayloadCount() > 0) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadList().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nexterdigital.nextershop.pb.csv.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nexterdigital.nextershop.pb.csv.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code csv.v1.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:csv.v1.Request)
      com.nexterdigital.nextershop.pb.csv.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nexterdigital.nextershop.pb.csv.CsvProto.internal_static_csv_v1_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nexterdigital.nextershop.pb.csv.CsvProto.internal_static_csv_v1_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nexterdigital.nextershop.pb.csv.Request.class, com.nexterdigital.nextershop.pb.csv.Request.Builder.class);
    }

    // Construct using com.nexterdigital.nextershop.pb.csv.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPayloadFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (payloadBuilder_ == null) {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        payloadBuilder_.clear();
      }
      id_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nexterdigital.nextershop.pb.csv.CsvProto.internal_static_csv_v1_Request_descriptor;
    }

    @java.lang.Override
    public com.nexterdigital.nextershop.pb.csv.Request getDefaultInstanceForType() {
      return com.nexterdigital.nextershop.pb.csv.Request.getDefaultInstance();
    }

    @java.lang.Override
    public com.nexterdigital.nextershop.pb.csv.Request build() {
      com.nexterdigital.nextershop.pb.csv.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nexterdigital.nextershop.pb.csv.Request buildPartial() {
      com.nexterdigital.nextershop.pb.csv.Request result = new com.nexterdigital.nextershop.pb.csv.Request(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      if (payloadBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.payload_ = payload_;
      } else {
        result.payload_ = payloadBuilder_.build();
      }
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nexterdigital.nextershop.pb.csv.Request) {
        return mergeFrom((com.nexterdigital.nextershop.pb.csv.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nexterdigital.nextershop.pb.csv.Request other) {
      if (other == com.nexterdigital.nextershop.pb.csv.Request.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (payloadBuilder_ == null) {
        if (!other.payload_.isEmpty()) {
          if (payload_.isEmpty()) {
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePayloadIsMutable();
            payload_.addAll(other.payload_);
          }
          onChanged();
        }
      } else {
        if (!other.payload_.isEmpty()) {
          if (payloadBuilder_.isEmpty()) {
            payloadBuilder_.dispose();
            payloadBuilder_ = null;
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000001);
            payloadBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPayloadFieldBuilder() : null;
          } else {
            payloadBuilder_.addAllMessages(other.payload_);
          }
        }
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nexterdigital.nextershop.pb.csv.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nexterdigital.nextershop.pb.csv.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.nexterdigital.nextershop.pb.csv.Payload> payload_ =
      java.util.Collections.emptyList();
    private void ensurePayloadIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        payload_ = new java.util.ArrayList<com.nexterdigital.nextershop.pb.csv.Payload>(payload_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nexterdigital.nextershop.pb.csv.Payload, com.nexterdigital.nextershop.pb.csv.Payload.Builder, com.nexterdigital.nextershop.pb.csv.PayloadOrBuilder> payloadBuilder_;

    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public java.util.List<com.nexterdigital.nextershop.pb.csv.Payload> getPayloadList() {
      if (payloadBuilder_ == null) {
        return java.util.Collections.unmodifiableList(payload_);
      } else {
        return payloadBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public int getPayloadCount() {
      if (payloadBuilder_ == null) {
        return payload_.size();
      } else {
        return payloadBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public com.nexterdigital.nextershop.pb.csv.Payload getPayload(int index) {
      if (payloadBuilder_ == null) {
        return payload_.get(index);
      } else {
        return payloadBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder setPayload(
        int index, com.nexterdigital.nextershop.pb.csv.Payload value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.set(index, value);
        onChanged();
      } else {
        payloadBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder setPayload(
        int index, com.nexterdigital.nextershop.pb.csv.Payload.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.set(index, builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder addPayload(com.nexterdigital.nextershop.pb.csv.Payload value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.add(value);
        onChanged();
      } else {
        payloadBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder addPayload(
        int index, com.nexterdigital.nextershop.pb.csv.Payload value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.add(index, value);
        onChanged();
      } else {
        payloadBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder addPayload(
        com.nexterdigital.nextershop.pb.csv.Payload.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.add(builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder addPayload(
        int index, com.nexterdigital.nextershop.pb.csv.Payload.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.add(index, builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder addAllPayload(
        java.lang.Iterable<? extends com.nexterdigital.nextershop.pb.csv.Payload> values) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payload_);
        onChanged();
      } else {
        payloadBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder clearPayload() {
      if (payloadBuilder_ == null) {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        payloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public Builder removePayload(int index) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.remove(index);
        onChanged();
      } else {
        payloadBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public com.nexterdigital.nextershop.pb.csv.Payload.Builder getPayloadBuilder(
        int index) {
      return getPayloadFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public com.nexterdigital.nextershop.pb.csv.PayloadOrBuilder getPayloadOrBuilder(
        int index) {
      if (payloadBuilder_ == null) {
        return payload_.get(index);  } else {
        return payloadBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public java.util.List<? extends com.nexterdigital.nextershop.pb.csv.PayloadOrBuilder> 
         getPayloadOrBuilderList() {
      if (payloadBuilder_ != null) {
        return payloadBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(payload_);
      }
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public com.nexterdigital.nextershop.pb.csv.Payload.Builder addPayloadBuilder() {
      return getPayloadFieldBuilder().addBuilder(
          com.nexterdigital.nextershop.pb.csv.Payload.getDefaultInstance());
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public com.nexterdigital.nextershop.pb.csv.Payload.Builder addPayloadBuilder(
        int index) {
      return getPayloadFieldBuilder().addBuilder(
          index, com.nexterdigital.nextershop.pb.csv.Payload.getDefaultInstance());
    }
    /**
     * <code>repeated .csv.v1.Payload payload = 2;</code>
     */
    public java.util.List<com.nexterdigital.nextershop.pb.csv.Payload.Builder> 
         getPayloadBuilderList() {
      return getPayloadFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nexterdigital.nextershop.pb.csv.Payload, com.nexterdigital.nextershop.pb.csv.Payload.Builder, com.nexterdigital.nextershop.pb.csv.PayloadOrBuilder> 
        getPayloadFieldBuilder() {
      if (payloadBuilder_ == null) {
        payloadBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.nexterdigital.nextershop.pb.csv.Payload, com.nexterdigital.nextershop.pb.csv.Payload.Builder, com.nexterdigital.nextershop.pb.csv.PayloadOrBuilder>(
                payload_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      return payloadBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 3;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 3;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:csv.v1.Request)
  }

  // @@protoc_insertion_point(class_scope:csv.v1.Request)
  private static final com.nexterdigital.nextershop.pb.csv.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nexterdigital.nextershop.pb.csv.Request();
  }

  public static com.nexterdigital.nextershop.pb.csv.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nexterdigital.nextershop.pb.csv.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

