// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.nexterdigitals.nextershop.pb.product;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sap_product_id = 1;</code>
   * @return The sapProductId.
   */
  java.lang.String getSapProductId();
  /**
   * <code>string sap_product_id = 1;</code>
   * @return The bytes for sapProductId.
   */
  com.google.protobuf.ByteString
      getSapProductIdBytes();

  /**
   * <code>string product_id = 2;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 2;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string category_id = 3;</code>
   * @return The categoryId.
   */
  java.lang.String getCategoryId();
  /**
   * <code>string category_id = 3;</code>
   * @return The bytes for categoryId.
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <code>string categories = 4;</code>
   * @return The categories.
   */
  java.lang.String getCategories();
  /**
   * <code>string categories = 4;</code>
   * @return The bytes for categories.
   */
  com.google.protobuf.ByteString
      getCategoriesBytes();

  /**
   * <code>string variant_id = 5;</code>
   * @return The variantId.
   */
  java.lang.String getVariantId();
  /**
   * <code>string variant_id = 5;</code>
   * @return The bytes for variantId.
   */
  com.google.protobuf.ByteString
      getVariantIdBytes();

  /**
   * <code>bool visible = 6;</code>
   * @return The visible.
   */
  boolean getVisible();

  /**
   * <code>string product_type = 7;</code>
   * @return The productType.
   */
  java.lang.String getProductType();
  /**
   * <code>string product_type = 7;</code>
   * @return The bytes for productType.
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();

  /**
   * <code>string name = 8;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 8;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string brand = 9;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 9;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>uint32 minimum_purchase = 10;</code>
   * @return The minimumPurchase.
   */
  int getMinimumPurchase();

  /**
   * <code>float service_charge = 11;</code>
   * @return The serviceCharge.
   */
  float getServiceCharge();

  /**
   * <code>string image = 12;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>string image = 12;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>string usage = 13;</code>
   * @return The usage.
   */
  java.lang.String getUsage();
  /**
   * <code>string usage = 13;</code>
   * @return The bytes for usage.
   */
  com.google.protobuf.ByteString
      getUsageBytes();

  /**
   * <code>string description = 14;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 14;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string specification = 15;</code>
   * @return The specification.
   */
  java.lang.String getSpecification();
  /**
   * <code>string specification = 15;</code>
   * @return The bytes for specification.
   */
  com.google.protobuf.ByteString
      getSpecificationBytes();

  /**
   * <code>string barcode = 16;</code>
   * @return The barcode.
   */
  java.lang.String getBarcode();
  /**
   * <code>string barcode = 16;</code>
   * @return The bytes for barcode.
   */
  com.google.protobuf.ByteString
      getBarcodeBytes();

  /**
   * <code>string article_id = 17;</code>
   * @return The articleId.
   */
  java.lang.String getArticleId();
  /**
   * <code>string article_id = 17;</code>
   * @return The bytes for articleId.
   */
  com.google.protobuf.ByteString
      getArticleIdBytes();

  /**
   * <code>string color = 18;</code>
   * @return The color.
   */
  java.lang.String getColor();
  /**
   * <code>string color = 18;</code>
   * @return The bytes for color.
   */
  com.google.protobuf.ByteString
      getColorBytes();

  /**
   * <code>string size = 19;</code>
   * @return The size.
   */
  java.lang.String getSize();
  /**
   * <code>string size = 19;</code>
   * @return The bytes for size.
   */
  com.google.protobuf.ByteString
      getSizeBytes();

  /**
   * <code>float price = 20;</code>
   * @return The price.
   */
  float getPrice();

  /**
   * <code>float special_price = 21;</code>
   * @return The specialPrice.
   */
  float getSpecialPrice();

  /**
   * <code>float shipping_cost = 22;</code>
   * @return The shippingCost.
   */
  float getShippingCost();

  /**
   * <code>string unit = 23;</code>
   * @return The unit.
   */
  java.lang.String getUnit();
  /**
   * <code>string unit = 23;</code>
   * @return The bytes for unit.
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <code>string unit_code = 24;</code>
   * @return The unitCode.
   */
  java.lang.String getUnitCode();
  /**
   * <code>string unit_code = 24;</code>
   * @return The bytes for unitCode.
   */
  com.google.protobuf.ByteString
      getUnitCodeBytes();

  /**
   * <code>string service = 25;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 25;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string keyword = 26;</code>
   * @return The keyword.
   */
  java.lang.String getKeyword();
  /**
   * <code>string keyword = 26;</code>
   * @return The bytes for keyword.
   */
  com.google.protobuf.ByteString
      getKeywordBytes();

  /**
   * <code>string type = 27;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 27;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string partner = 28;</code>
   * @return The partner.
   */
  java.lang.String getPartner();
  /**
   * <code>string partner = 28;</code>
   * @return The bytes for partner.
   */
  com.google.protobuf.ByteString
      getPartnerBytes();

  /**
   * <code>string phase_type = 29;</code>
   * @return The phaseType.
   */
  java.lang.String getPhaseType();
  /**
   * <code>string phase_type = 29;</code>
   * @return The bytes for phaseType.
   */
  com.google.protobuf.ByteString
      getPhaseTypeBytes();

  /**
   * <code>string shipping_type = 30;</code>
   * @return The shippingType.
   */
  java.lang.String getShippingType();
  /**
   * <code>string shipping_type = 30;</code>
   * @return The bytes for shippingType.
   */
  com.google.protobuf.ByteString
      getShippingTypeBytes();

  /**
   * <code>string pattern_tiles = 31;</code>
   * @return The patternTiles.
   */
  java.lang.String getPatternTiles();
  /**
   * <code>string pattern_tiles = 31;</code>
   * @return The bytes for patternTiles.
   */
  com.google.protobuf.ByteString
      getPatternTilesBytes();

  /**
   * <code>uint32 pack_in_box = 32;</code>
   * @return The packInBox.
   */
  int getPackInBox();

  /**
   * <code>string tile_square = 33;</code>
   * @return The tileSquare.
   */
  java.lang.String getTileSquare();
  /**
   * <code>string tile_square = 33;</code>
   * @return The bytes for tileSquare.
   */
  com.google.protobuf.ByteString
      getTileSquareBytes();

  /**
   * <code>string variant_image = 34;</code>
   * @return The variantImage.
   */
  java.lang.String getVariantImage();
  /**
   * <code>string variant_image = 34;</code>
   * @return The bytes for variantImage.
   */
  com.google.protobuf.ByteString
      getVariantImageBytes();

  /**
   * <code>string product_image = 35;</code>
   * @return The productImage.
   */
  java.lang.String getProductImage();
  /**
   * <code>string product_image = 35;</code>
   * @return The bytes for productImage.
   */
  com.google.protobuf.ByteString
      getProductImageBytes();
}
