name: CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROTOC_GEN_GRPC_KOTLIN_VERSION: '1.0.0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Bump project version
        run: |
          git config user.email kekhuay@users.noreply.github.com
          git config user.name 'Natthaphon Phanit'
          ./gradlew clean release -Prelease.useAutomaticVersion=true -Pusr=${{ secrets.REPSY_NEXTER_DIGITAL_REPOSITORY_USERNAME }} -Ppwd=${{ secrets.REPSY_NEXTER_DIGITAL_REPOSITORY_PASSWORD }}
