name: Bump version and publish the artifact to remote repository

# Controls when the action will run.
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROTOC_GEN_GRPC_KOTLIN_VERSION: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Main process
        run: |
          git config user.email kekhuay@users.noreply.github.com
          git config user.name 'Natthaphon Phanit'
          ./gradlew clean release -Prelease.useAutomaticVersion=true -Pusr=${{ secrets.REPSY_NEXTER_DIGITAL_REPOSITORY_USERNAME }} -Ppwd=${{ secrets.REPSY_NEXTER_DIGITAL_REPOSITORY_PASSWORD }}
          ./gradlew clean publish -Pusr=${{ secrets.REPSY_NEXTER_DIGITAL_REPOSITORY_USERNAME }} -Ppwd=${{ secrets.REPSY_NEXTER_DIGITAL_REPOSITORY_PASSWORD }}
